use super::{
    AR, I, IMAGE_SIZE, IMG_RES, ModelSpec, NO_FIELD, OF_JPEG, OF_JPG, OF_NONE, OUT_RES, QUALITY,
    RATIO, RES, V, model, no_prompt, optional_prompt, profile, ua, ufr, ufrf, un, us,
};

// Data-only catalog: keep matching and request-assembly behavior in the parent module.
#[rustfmt::skip]
pub(super) static MODELS: &[ModelSpec] = &[
    model("bytedance/seedream", "Seedream3.0 - Text to Image", I, profile(un(), NO_FIELD, NO_FIELD, OF_NONE), &[]),
    model("bytedance/seedream-v4-text-to-image", "Seedream4.0 - Text to Image", I, profile(un(), NO_FIELD, IMG_RES, OF_NONE), &[]),
    model("bytedance/seedream-v4-edit", "Seedream4.0 - Edit", I, profile(ua("image_urls", Some(10)), NO_FIELD, IMG_RES, OF_NONE), &[]),
    model("seedream/4.5-text-to-image", "Seedream4.5 - Text to Image", I, profile(un(), AR, QUALITY, OF_NONE), &[]),
    model("seedream/4.5-edit", "Seedream4.5 - Edit", I, profile(ua("image_urls", Some(14)), AR, QUALITY, OF_NONE), &[]),
    model("seedream/5-lite-text-to-image", "Seedream5.0 Lite - Text to Image", I, profile(un(), AR, QUALITY, OF_JPEG), &[]),
    model("seedream/5-lite-image-to-image", "Seedream5.0 Lite - Image to Image", I, profile(ua("image_urls", Some(14)), AR, QUALITY, OF_JPEG), &[]),
    model("seedream/5-pro-text-to-image", "Seedream5.0 Pro - Text to Image", I, profile(un(), AR, QUALITY, OF_JPEG), &[]),
    model("seedream/5-pro-image-to-image", "Seedream5.0 Pro - Image to Image", I, profile(ua("image_urls", Some(10)), AR, QUALITY, OF_JPEG), &[]),
    model("z-image", "Z-Image", I, profile(un(), AR, NO_FIELD, OF_NONE), &[]),
    model("google/imagen4-fast", "Google - imagen4-fast", I, profile(un(), AR, NO_FIELD, OF_NONE), &[]),
    model("google/imagen4-ultra", "Google - imagen4-ultra", I, profile(un(), AR, NO_FIELD, OF_NONE), &[]),
    model("google/imagen4", "Google - imagen4", I, profile(un(), AR, NO_FIELD, OF_NONE), &[]),
    model("google/nano-banana-edit", "Google - Nano Banana Edit", I, profile(ua("image_urls", Some(10)), AR, NO_FIELD, OF_JPEG), &["Nano Banana Edit"]),
    model("google/nano-banana", "Google - Nano Banana", I, profile(un(), AR, NO_FIELD, OF_JPEG), &["Nano Banana"]),
    model("nano-banana-pro", "Google - Nano Banana Pro", I, profile(ua("image_input", Some(8)), AR, RES, OF_JPG), &["Nano Banana Pro", "NanoBananaPro"]),
    model("nano-banana-2", "Google - Nano Banana 2", I, profile(ua("image_input", Some(14)), AR, RES, OF_JPG), &["Nano Banana 2", "NanoBanana2"]),
    model("nano-banana-2-lite", "Google - Nano Banana 2 Lite", I, profile(ua("image_urls", Some(10)), AR, NO_FIELD, OF_NONE), &["Nano Banana 2 Lite", "NanoBanana2Lite"]),
    model("flux-2/pro-image-to-image", "Flux-2 - Pro Image to Image", I, profile(ua("input_urls", Some(8)), AR, RES, OF_NONE), &[]),
    model("flux-2/pro-text-to-image", "Flux-2 - Pro Text to Image", I, profile(un(), AR, RES, OF_NONE), &[]),
    model("flux-2/flex-image-to-image", "Flux-2 - Image to Image", I, profile(ua("input_urls", Some(8)), AR, RES, OF_NONE), &[]),
    model("flux-2/flex-text-to-image", "Flux-2 - Text to Image", I, profile(un(), AR, RES, OF_NONE), &[]),
    model("grok-imagine/text-to-image", "Grok Imagine - Text to Image", I, profile(un(), AR, NO_FIELD, OF_NONE), &[]),
    model("grok-imagine/image-to-image", "Grok Imagine - image to image", I, optional_prompt(profile(ua("image_urls", Some(5)), NO_FIELD, NO_FIELD, OF_NONE)), &[]),
    model("gpt-image/1.5-text-to-image", "GPT Image-1.5 - Text to Image", I, profile(un(), AR, QUALITY, OF_NONE), &[]),
    model("gpt-image/1.5-image-to-image", "GPT Image-1.5 - Image to Image", I, profile(ua("input_urls", Some(16)), AR, QUALITY, OF_NONE), &[]),
    model("gpt-image-2-text-to-image", "GPT Image-2 - Text to Image", I, profile(un(), AR, RES, OF_NONE), &["GPT Image 2 Text To Image"]),
    model("gpt-image-2-image-to-image", "GPT Image 2 - Image To Image", I, profile(ua("input_urls", Some(16)), AR, RES, OF_NONE), &["GPT Image 2 Image To Image"]),
    model("topaz/image-upscale", "Topaz - Image Upscale", I, no_prompt(profile(us("image_url"), NO_FIELD, NO_FIELD, OF_NONE)), &[]),
    model("recraft/remove-background", "Recraft - Remove Background", I, no_prompt(profile(us("image"), NO_FIELD, NO_FIELD, OF_NONE)), &[]),
    model("recraft/crisp-upscale", "Recraft - Crisp Upscale", I, no_prompt(profile(us("image"), NO_FIELD, NO_FIELD, OF_NONE)), &[]),
    model("ideogram/character-edit", "Ideogram - Character Edit", I, profile(un(), NO_FIELD, NO_FIELD, OF_NONE), &[]),
    model("ideogram/character-remix", "Ideogram - Character Remix", I, profile(un(), NO_FIELD, NO_FIELD, OF_NONE), &[]),
    model("ideogram/character", "Ideogram - Character", I, profile(ua("reference_image_urls", Some(1)), NO_FIELD, NO_FIELD, OF_NONE), &[]),
    model("ideogram/v3-text-to-image", "Ideogram V3 Text to Image", I, profile(un(), NO_FIELD, NO_FIELD, OF_NONE), &[]),
    model("ideogram/v3-edit", "Ideogram V3 Edit", I, profile(us("image_url"), NO_FIELD, NO_FIELD, OF_NONE), &[]),
    model("ideogram/v3-remix", "Ideogram V3 Remix", I, profile(us("image_url"), NO_FIELD, NO_FIELD, OF_NONE), &[]),
    model("qwen/text-to-image", "Qwen - Text to Image", I, profile(un(), NO_FIELD, NO_FIELD, OF_JPEG), &[]),
    model("qwen/image-to-image", "Qwen - Image to Image", I, profile(us("image_url"), NO_FIELD, NO_FIELD, OF_JPEG), &[]),
    model("qwen/image-edit", "Qwen - Image Edit", I, profile(us("image_url"), NO_FIELD, NO_FIELD, OF_JPEG), &[]),
    model("qwen2/image-edit", "Qwen2 - Image Edit", I, profile(us("image_url"), IMAGE_SIZE, NO_FIELD, OF_JPEG), &[]),
    model("qwen2/text-to-image", "Qwen2 - Text To Image", I, profile(un(), IMAGE_SIZE, NO_FIELD, OF_JPEG), &[]),
    model("wan/2-7-image", "Wan 2.7 Image", I, profile(ua("input_urls", Some(9)), AR, RES, OF_NONE), &[]),
    model("wan/2-7-image-pro", "Wan 2.7 Image Pro", I, profile(ua("input_urls", Some(9)), AR, RES, OF_NONE), &[]),
    model("grok-imagine/text-to-video", "Grok Imagine Text to Video", V, profile(un(), AR, RES, OF_NONE), &[]),
    model("grok-imagine/image-to-video", "Grok Imagine Image to Video", V, optional_prompt(profile(ua("image_urls", Some(7)), AR, RES, OF_NONE)), &[]),
    model("grok-imagine/upscale", "Grok Imagine - Video Upscale", V, no_prompt(profile(un(), NO_FIELD, NO_FIELD, OF_NONE)), &[]),
    model("grok-imagine/extend", "Grok Imagine - Video Extend", V, profile(un(), NO_FIELD, NO_FIELD, OF_NONE), &[]),
    model("grok-imagine-video-1-5-preview", "Grok Imagine Video 1.5 Preview", V, optional_prompt(profile(ua("image_urls", Some(7)), AR, RES, OF_NONE)), &[]),
    model("kling-2.6/text-to-video", "Kling 2.6 Text to Video", V, profile(un(), AR, NO_FIELD, OF_NONE), &[]),
    model("kling-2.6/image-to-video", "Kling 2.6 Image to Video", V, profile(ua("image_urls", Some(1)), NO_FIELD, NO_FIELD, OF_NONE), &[]),
    model("kling/v2-1-master-image-to-video", "Kling V2.1 Master Image to Video", V, profile(us("image_url"), NO_FIELD, NO_FIELD, OF_NONE), &[]),
    model("kling/v2-5-turbo-image-to-video-pro", "Kling - V2.5 Turbo Image to Video Pro", V, profile(ufrf("image_url", "tail_image_url"), NO_FIELD, NO_FIELD, OF_NONE), &[]),
    model("kling/v2-5-turbo-text-to-video-pro", "Kling - V2.5 Turbo Text to Video Pro", V, profile(un(), AR, NO_FIELD, OF_NONE), &[]),
    model("kling/ai-avatar-standard", "Kling AI Avatar Standard", V, profile(un(), NO_FIELD, NO_FIELD, OF_NONE), &[]),
    model("kling/ai-avatar-pro", "Kling AI Avatar Pro", V, profile(un(), NO_FIELD, NO_FIELD, OF_NONE), &[]),
    model("kling/v2-1-master-text-to-video", "Kling V2.1 Master Text to Video", V, profile(un(), AR, NO_FIELD, OF_NONE), &[]),
    model("kling/v2-1-pro", "Kling V2.1 Pro", V, profile(ufrf("image_url", "tail_image_url"), NO_FIELD, NO_FIELD, OF_NONE), &[]),
    model("kling/v2-1-standard", "Kling V2.1 Standard", V, profile(us("image_url"), NO_FIELD, NO_FIELD, OF_NONE), &[]),
    model("kling-2.6/motion-control", "Kling 2.6 motion-control", V, optional_prompt(profile(un(), NO_FIELD, NO_FIELD, OF_NONE)), &[]),
    model("kling-3.0/motion-control", "Kling-3.0 motion-control", V, optional_prompt(profile(un(), NO_FIELD, NO_FIELD, OF_NONE)), &[]),
    model("kling-3.0/video", "Kling 3.0", V, profile(ua("image_urls", Some(2)), AR, NO_FIELD, OF_NONE), &[]),
    model("kling/v3-turbo-text-to-video", "Kling - V3 Turbo Text to Video", V, profile(un(), AR, RES, OF_NONE), &[]),
    model("kling/v3-turbo-image-to-video", "Kling - V3 Turbo Image to Video", V, profile(ua("image_urls", Some(1)), NO_FIELD, RES, OF_NONE), &[]),
    model("bytedance/seedance-2", "bytedance-seedance-2", V, profile(ufr(), AR, RES, OF_NONE), &[]),
    model("bytedance/seedance-2-fast", "Bytedance Seedance 2.0 Fast", V, profile(ufr(), AR, RES, OF_NONE), &[]),
    model("bytedance/seedance-2-mini", "Bytedance Seedance 2.0 Mini", V, profile(ufr(), AR, RES, OF_NONE), &[]),
    model("bytedance/seedance-1.5-pro", "Bytedance Seedance 1.5 Pro", V, profile(ua("input_urls", Some(2)), AR, RES, OF_NONE), &[]),
    model("bytedance/v1-pro-fast-image-to-video", "Bytedance V1 Pro Fast Image to Video", V, profile(us("image_url"), NO_FIELD, RES, OF_NONE), &[]),
    model("bytedance/v1-pro-image-to-video", "Bytedance V1 Pro Image to Video", V, profile(us("image_url"), NO_FIELD, RES, OF_NONE), &[]),
    model("bytedance/v1-pro-text-to-video", "Bytedance - V1 Pro Text to Video", V, profile(un(), AR, RES, OF_NONE), &[]),
    model("bytedance/v1-lite-image-to-video", "Bytedance - V1 Lite Image to Video", V, profile(ufrf("image_url", "end_image_url"), NO_FIELD, RES, OF_NONE), &[]),
    model("bytedance/v1-lite-text-to-video", "Bytedance - V1 Lite Text to Video", V, profile(un(), AR, RES, OF_NONE), &[]),
    model("hailuo/2-3-image-to-video-pro", "Hailuo 2.3 Pro Image to Video", V, profile(us("image_url"), NO_FIELD, RES, OF_NONE), &[]),
    model("hailuo/2-3-image-to-video-standard", "Hailuo 2.3 Standard Image to Video", V, profile(us("image_url"), NO_FIELD, RES, OF_NONE), &[]),
    model("hailuo/02-text-to-video-pro", "Hailuo Pro Text to Video", V, profile(un(), NO_FIELD, NO_FIELD, OF_NONE), &[]),
    model("hailuo/02-image-to-video-pro", "Hailuo Pro Image to Video", V, profile(ufrf("image_url", "end_image_url"), NO_FIELD, NO_FIELD, OF_NONE), &[]),
    model("hailuo/02-text-to-video-standard", "Hailuo Standard Text to Video", V, profile(un(), NO_FIELD, NO_FIELD, OF_NONE), &[]),
    model("hailuo/02-image-to-video-standard", "Hailuo Standard Image to Video", V, profile(ufrf("image_url", "end_image_url"), NO_FIELD, RES, OF_NONE), &[]),
    model("wan/2-2-a14b-image-to-video-turbo", "Wan - Image to Video", V, profile(us("image_url"), NO_FIELD, RES, OF_NONE), &[]),
    model("wan/2-2-a14b-speech-to-video-turbo", "Wan - 2.2 A14B Speech to Video Turbo", V, profile(un(), NO_FIELD, RES, OF_NONE), &[]),
    model("wan/2-2-a14b-text-to-video-turbo", "Wan - Text to Video", V, profile(un(), AR, RES, OF_NONE), &[]),
    model("wan/2-2-animate-move", "Wan - Animate Move", V, no_prompt(profile(un(), NO_FIELD, RES, OF_NONE)), &[]),
    model("wan/2-2-animate-replace", "Wan - Animate Replace", V, no_prompt(profile(un(), NO_FIELD, RES, OF_NONE)), &[]),
    model("wan/2-6-image-to-video", "Wan 2.6 - Image to Video", V, profile(ua("image_urls", Some(1)), NO_FIELD, RES, OF_NONE), &[]),
    model("wan/2-6-text-to-video", "Wan 2.6 - Text to Video", V, profile(un(), NO_FIELD, RES, OF_NONE), &[]),
    model("wan/2-6-video-to-video", "Wan 2.6 - Video to Video", V, profile(ua("video_urls", Some(3)), NO_FIELD, RES, OF_NONE), &[]),
    model("wan/2-6-flash-image-to-video", "Wan - 2.6-flash-image-to-video", V, profile(ua("image_urls", Some(1)), NO_FIELD, RES, OF_NONE), &[]),
    model("wan/2-6-flash-video-to-video", "Wan - 2-6-flash-video-to-video", V, profile(ua("video_urls", Some(3)), NO_FIELD, RES, OF_NONE), &[]),
    model("wan/2-5-image-to-video", "Wan 2.5 - Image to Video", V, profile(us("image_url"), NO_FIELD, RES, OF_NONE), &[]),
    model("wan/2-5-text-to-video", "Wan 2.5 - Text to Video", V, profile(un(), AR, RES, OF_NONE), &[]),
    model("wan/2-7-text-to-video", "Wan 2.7 - Text to Video", V, profile(un(), RATIO, RES, OF_NONE), &[]),
    model("wan/2-7-image-to-video", "Wan 2.7 - Image to Video", V, profile(ufr(), NO_FIELD, RES, OF_NONE), &[]),
    model("wan/2-7-videoedit", "Wan 2.7 - Video Edit", V, optional_prompt(profile(us("video_url"), AR, RES, OF_NONE)), &[]),
    model("wan/2-7-r2v", "Wan 2.7 - Reference to Video", V, profile(un(), AR, RES, OF_NONE), &[]),
    model("topaz/video-upscale", "Topaz - Video Upscale", V, no_prompt(profile(us("video_url"), NO_FIELD, NO_FIELD, OF_NONE)), &[]),
    model("infinitalk/from-audio", "Infinitalk - From Audio", V, profile(un(), NO_FIELD, RES, OF_NONE), &[]),
    model("pixverse-v6/text-to-video", "PixVerse V6 Text-to-Video", V, profile(un(), AR, QUALITY, OF_NONE), &[]),
    model("pixverse-v6/image-to-video", "PixVerse V6 Image-to-Video", V, profile(ua("image_urls", Some(2)), NO_FIELD, QUALITY, OF_NONE), &[]),
    model("pixverse-v6/transition", "PixVerse V6 First & Last Frame Transition", V, profile(ufrf("first_frame_image_url", "last_frame_image_url"), NO_FIELD, QUALITY, OF_NONE), &[]),
    model("pixverse-v6/extend", "PixVerse V6 Video Extension", V, profile(us("video_url"), NO_FIELD, QUALITY, OF_NONE), &[]),
    model("pixverse-v6/reference-to-video", "PixVerse V6 Fusion / Reference-to-Video", V, profile(un(), AR, QUALITY, OF_NONE), &[]),
    model("happyhorse/text-to-video", "happyhorse-text-to-video", V, profile(un(), AR, RES, OF_NONE), &[]),
    model("happyhorse/image-to-video", "happyhorse-image-to-video", V, optional_prompt(profile(ua("image_urls", Some(1)), NO_FIELD, RES, OF_NONE)), &[]),
    model("happyhorse/reference-to-video", "happyhorse/reference-to-video", V, profile(ua("reference_image", Some(9)), AR, RES, OF_NONE), &[]),
    model("happyhorse/video-edit", "happyhorse/video-edit", V, profile(us("video_url"), NO_FIELD, RES, OF_NONE), &[]),
    model("happyhorse-1-1/image-to-video", "HappyHorse-1-1 image-to-video", V, optional_prompt(profile(ua("image_urls", Some(1)), NO_FIELD, RES, OF_NONE)), &[]),
    model("happyhorse-1-1/text-to-video", "HappyHorse-1-1 text-to-video", V, profile(un(), AR, RES, OF_NONE), &[]),
    model("happyhorse-1-1/reference-to-video", "HappyHorse-1-1 reference-to-video", V, profile(ua("reference_image", Some(9)), AR, RES, OF_NONE), &[]),
    model("gemini-omni-video", "Gemini Omni Video", V, profile(ua("image_urls", Some(7)), AR, RES, OF_NONE), &[]),
    model("omnihuman-1-5", "Omnihuman 1.5", V, optional_prompt(profile(un(), NO_FIELD, OUT_RES, OF_NONE)), &[]),
    model("volcengine/video-to-video-lip-sync", "Volcengine video to video lip sync", V, no_prompt(profile(un(), NO_FIELD, NO_FIELD, OF_NONE)), &[]),
];
